### ISSUE TITLE
allow trailing commas everywhere

### ISSUE THREAD

**Issue by jt3k** [blond/eslint-config-pedant#57]
what about allow to set trailing-comma in function calls/params and other places?

In es2015 trailing comma is ok in some places
see here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

I suggest to apply this rule in the default pedant config (not for es3, es5)

**Comment by qfox** [comment]
I'm not sure it's a good idea because trailing comma is a stylistic thing for ES2015+.

Pedant was written especially for common mistakes which potentially can broke the whole your script.
Since this thing is not a problem for modern ES I'm against puttin it to the default preset.

**Comment by jt3k** [comment]
trailing-comma is a stylistic thing, but its presence or absence will not do anything wrong with the modern_ES

Nevertheless, the pedant swears at this construction: 
```
myFunc(
  a,
  b,
  c,
);
```

**Comment by jt3k** [comment]
@zxqfox 
it seems that you do not understand me.
I for that not to forbid to put a comma in the end of set.
Now there is an error with the supplied trailing-comma
![](https://i.imgur.com/Vg01jvn.png)

**Comment by jt3k** [comment]
hmm, maybe it just does not work for me. Created related issue #59

**Comment by blond** [comment]
@jt3k It does not depend on `eslint-config-pedant`. 

In ECMAScript 2015 or below trailing commas in functions is not working.

From the documentation of [comma-dangle](https://eslint.org/docs/rules/comma-dangle#options) rule:

> functions is for function declarations and function calls. (e.g. (function(a,){ })(b,);)
functions is set to "ignore" by default for consistency with the string option.
functions should only be enabled when linting ECMAScript 2017 or higher.

**Example:**

`test.js`
```js
const sum = (a, b) => a + b;
const res = sum(2, 1,);

console.log(res);
```

```shell
$ nvm use 4
$ node ./test.js
Parsing error: Unexpected token.

$ nvm use 8
$ node ./test.js
3
```

You are getting those errors, because you haven't specified `ecmaVersion: 2017` under [parserOptions](http://eslint.org/docs/user-guide/configuring#specifying-parser-options).

**Comment by jt3k** [comment]
!!! thanks. now i understand!
